### ISSUE TITLE
Open issue about remote dependencies

### ISSUE THREAD

**Issue by pburkholder** [pburkholder/ato1day-compliance#20]
This issue is my scratch space for gathering my thoughts to open an issue in `discuss`

To wit:
- `url` seems to require not a URL, but a path to Git repo
- The repo seems to require a top-level `opencontrol.yaml` even though it might be sensible to nest that as in freedonia-aws/compliance/opencontrol.yaml
- the `dependencies` field should support an numbered/signed release/archive

See also: https://github.com/opencontrol/discuss/issues/4

Perhaps something like the following for 5 different systems:

```
dependencies:
  systems:
    - repository: https://bitbucket.com/org/repo
      path: ./docs/compliance/opencontrol.yaml
      revision: master
    - archive: https://github.com/opencontrol/compliance-masonry/archive/v1.1.1.tar.gz
      signature: https://github.com/opencontrol/compliance-masonry/archive/v1.1.1.tar.gz.asc
      path: ./docs/compliance/opencontrol.yaml
    - url: https://path/to/url/not/a/repo/opencontrol.yaml
    - url: file://my/path/to/some/wip/opencontrol.yaml
    - repository: file://my/path/to/git/repo
      path: ./docs/compliance/opencontrol.yaml
      revision: master
```

Why is there a benefit to cloning git repos locally?

archive would be best for assurance purposes
url or repository
